---
- hosts: build-servers
  sudo: true
  tasks:
   - name: install git
     yum: pkg=git
   - name: install javac
     yum: pkg=java-1.7.0-openjdk-devel
   - name: install maven
     yum: pkg=maven
   - name: install gpg2
     yum: pkg=gnupg2
