---
- hosts: build-servers
  user: ubuntu
  tasks:
   - name: checkout code
     git: repo=https://github.com/alexec/docker.git dest=docker track_submodules=true
   #- name: build docker-java-orchestrator
   #  shell:
   #  - chdir: docker/docker-java-orchestrator
   #  -
