---
- hosts: build-servers
  vars:
  - dir: docker-maven-plugin
  tasks:
  - include: tasks/checkout.yml
  - include: tasks/use-release-versions.yml
  - include: tasks/release.yml
  - include: tasks/open-snapshots.yml
