  - name: release
    shell: mvn versions:use-latest-snapshots -Dincludes='com.alexecollins.docker:*'
    args:
      chdir: "{{ dir }}"
  - name: commit versions
    shell: git commit -m 'updated to latest snapshot versions' -- pom.xml
    args:
      chdir: "{{ dir }}"
  - name: push
    shell: git push
    args:
      chdir: "{{ dir }}"
